from accounts.models import ReservationDeactivationMonth,RequestItem,RequestItemChoice,CartItem,CartItemChoice,BoughtItemChoice,BoughtCheck,User,ArticleDislike,UserDislike,RequestImage,RequestForm,RequestCheckbox,UserView,Request,Article,ArticleImage,ArticleSharedImage,ArticleBookmark,ArticleVideo,ArticleTag,ArticleView,ArticleLike,ArticleUserTag,ArticleComment,CalendarDate,CalendarSchedule,UserReport,UserMessage,UserBlock,UserTag,UserComment,UserFollow,UserLike,UserImage,UserPhone,UserLocation,UserMail,ArticleSharedVideo,CalendarTime,UserCalendarType,CalendarStatus,ArticleCommentDislike,UserCommentDislike,ArticleCommentLike,UserCommentLike,ArticleCategory,ArticleChoiceCategory,ArticleChoice,ArticleForm,ArticleCheckbox,ReservationSchedule,UserCartItem,ArticleActivity,ArticleHighlight,ArticleTravelLocation,BusinessType,ArticleAmenity,ArticleDetailCategory,ArticleDetailIncluded,ArticleDetailRule,ArticleDetailSpec,ItemType,UserOpeningHour,MeetingStatus,MeetingSchedule
from django.contrib import admin
from rest_framework.authtoken.admin import TokenAdmin

TokenAdmin.raw_id_fields = ['user']
admin.site.register(User)

admin.site.register(MeetingStatus)
admin.site.register(MeetingSchedule)
admin.site.register(ArticleActivity)
admin.site.register(ArticleHighlight)
admin.site.register(ArticleTravelLocation)
admin.site.register(ArticleAmenity)
admin.site.register(ArticleDetailCategory)
admin.site.register(ArticleDetailRule)
admin.site.register(ArticleDetailIncluded)
admin.site.register(ArticleDetailSpec)
admin.site.register(UserOpeningHour)
admin.site.register(BusinessType)
admin.site.register(BoughtCheck)
admin.site.register(ItemType)
admin.site.register(RequestItem)
admin.site.register(RequestItemChoice)
admin.site.register(BoughtItemChoice)
admin.site.register(UserCartItem)
admin.site.register(CartItem)
admin.site.register(CartItemChoice)
admin.site.register(ArticleCommentDislike)
admin.site.register(ArticleCategory)
admin.site.register(ArticleChoiceCategory)
admin.site.register(ArticleChoice)
admin.site.register(ArticleForm)
admin.site.register(ArticleCheckbox)
admin.site.register(UserCommentDislike)
admin.site.register(ArticleCommentLike)
admin.site.register(UserCommentLike)
admin.site.register(Request)
admin.site.register(RequestImage)
admin.site.register(RequestForm)
admin.site.register(RequestCheckbox)
admin.site.register(UserReport)
admin.site.register(ArticleDislike)
admin.site.register(UserDislike)
admin.site.register(UserCalendarType)
admin.site.register(UserMessage)
admin.site.register(UserBlock)
admin.site.register(UserTag)
admin.site.register(UserView)
admin.site.register(UserImage)
admin.site.register(UserMail)
admin.site.register(UserPhone)
admin.site.register(UserLocation)
admin.site.register(UserComment)
admin.site.register(UserFollow)
admin.site.register(UserLike)
admin.site.register(Article)
admin.site.register(ArticleImage)
admin.site.register(ArticleSharedImage)
admin.site.register(ArticleSharedVideo)
admin.site.register(ArticleBookmark)
admin.site.register(ArticleVideo)
admin.site.register(ArticleTag)
admin.site.register(ArticleView)
admin.site.register(ArticleLike)
admin.site.register(ArticleUserTag)
admin.site.register(ArticleComment)
admin.site.register(CalendarTime)
admin.site.register(CalendarDate)
admin.site.register(CalendarStatus)
admin.site.register(CalendarSchedule)
admin.site.register(ReservationSchedule)
admin.site.register(ReservationDeactivationMonth)








